@echo off
md "Arcade\Pinball"
md "roms\Ball and Paddle\Breakout"
md "roms\Ball and Paddle\Jump and Touch"
md "roms\Ball and Paddle\Misc"
md "roms\Ball and Paddle\Pong"
md "roms\Climbing\Building"
md "roms\Climbing\Mountain - Wall"
md "roms\Climbing\Tree - Plant"
md "roms\Driving\1st Person"
md "roms\Driving\Ambulance Guide"
md "roms\Driving\Boat"
md "roms\Driving\Demolition Derby"
md "roms\Driving\FireTruck Guide"
md "roms\Driving\Guide and Collect"
md "roms\Driving\Guide and Shoot"
md "roms\Driving\Landing"
md "roms\Driving\Misc"
md "roms\Driving\Motorbike (Motocross)"
md "roms\Driving\Motorbike"
md "roms\Driving\Plane"
md "roms\Driving\Race (chase view) Bike"
md "roms\Driving\Race (chase view)"
md "roms\Driving\Race 1st Person"
md "roms\Driving\Race Bike"
md "roms\Driving\Race Track"
md "roms\Driving\Race"
md "roms\Driving\Truck Guide"
md "roms\Fighter\2.5D"
md "roms\Fighter\2D"
md "roms\Fighter\3D"
md "roms\Fighter\Driving Vertical"
md "roms\Fighter\Field"
md "roms\Fighter\Misc"
md "roms\Fighter\Multiplay"
md "roms\Fighter\Versus Co-op"
md "roms\Fighter\Versus"
md "roms\Fighter\Vertical"
md "roms\Mature\Arcade\Pinball"
md "roms\Mature\Ball and Paddle\Breakout"
md "roms\Mature\Fighter\Versus"
md "roms\Mature\Maze\Blocks"
md "roms\Mature\Maze\Collect"
md "roms\Mature\Maze\Digging"
md "roms\Mature\Maze\Driving"
md "roms\Mature\Maze\Escape"
md "roms\Mature\MultiGame\Compilation"
md "roms\Mature\Multiplay\Mini-Games"
md "roms\Mature\Multiplay\Misc"
md "roms\Mature\Platform\Run Jump"
md "roms\Mature\Puzzle\Drop"
md "roms\Mature\Puzzle\Match"
md "roms\Mature\Puzzle\Misc"
md "roms\Mature\Puzzle\Outline"
md "roms\Mature\Puzzle\Paint"
md "roms\Mature\Puzzle\Reconstruction"
md "roms\Mature\Puzzle\Sliding"
md "roms\Mature\Puzzle\Toss"
md "roms\Mature\Shooter\Flying Horizontal"
md "roms\Mature\Shooter\Flying Vertical"
md "roms\Mature\Shooter\Flying"
md "roms\Mature\Shooter\Gallery"
md "roms\Mature\Shooter\Outline"
md "roms\Mature\Sports\Pool"
md "roms\Maze\Ball Guide"
md "roms\Maze\Blocks"
md "roms\Maze\Change Surface"
md "roms\Maze\Collect and Put"
md "roms\Maze\Collect"
md "roms\Maze\Cross"
md "roms\Maze\Defeat Enemies"
md "roms\Maze\Digging"
md "roms\Maze\Driving"
md "roms\Maze\Escape"
md "roms\Maze\Fighter"
md "roms\Maze\Integrate"
md "roms\Maze\Ladders"
md "roms\Maze\Marble Madness"
md "roms\Maze\Misc"
md "roms\Maze\Move and Sort"
md "roms\Maze\Outline"
md "roms\Maze\Paint"
md "roms\Maze\Run Jump"
md "roms\Maze\Shooter Large"
md "roms\Maze\Shooter Small"
md "roms\Maze\Surround"
md "roms\MultiGame\Compilation"
md "roms\MultiGame\Mini-Games"
md "roms\Multiplay\Mini-Games"
md "roms\Platform\Fighter Scrolling"
md "roms\Platform\Fighter"
md "roms\Platform\Maze"
md "roms\Platform\Run Jump"
md "roms\Platform\Run, Jump and Scrolling"
md "roms\Platform\Shooter Scrolling"
md "roms\Platform\Shooter"
md "roms\Puzzle\Cards"
md "roms\Puzzle\Drop"
md "roms\Puzzle\Match"
md "roms\Puzzle\Maze"
md "roms\Puzzle\Misc"
md "roms\Puzzle\Outline"
md "roms\Puzzle\Reconstruction"
md "roms\Puzzle\Sliding"
md "roms\Puzzle\Toss"
md "roms\Shooter\1st Person"
md "roms\Shooter\3rd Person"
md "roms\Shooter\Command"
md "roms\Shooter\Driving (chase view)"
md "roms\Shooter\Driving 1st Person"
md "roms\Shooter\Driving Diagonal"
md "roms\Shooter\Driving Horizontal"
md "roms\Shooter\Driving Vertical"
md "roms\Shooter\Driving"
md "roms\Shooter\Field"
md "roms\Shooter\Flying (chase view)"
md "roms\Shooter\Flying 1st Person"
md "roms\Shooter\Flying Diagonal"
md "roms\Shooter\Flying Horizontal"
md "roms\Shooter\Flying Vertical"
md "roms\Shooter\Flying"
md "roms\Shooter\Gallery"
md "roms\Shooter\Gun"
md "roms\Shooter\Misc Horizontal"
md "roms\Shooter\Misc Vertical"
md "roms\Shooter\Misc"
md "roms\Shooter\Underwater"
md "roms\Shooter\Versus"
md "roms\Shooter\Walking"
md "roms\Sports\Armwrestling"
md "roms\Sports\Baseball"
md "roms\Sports\Basketball"
md "roms\Sports\Bowling"
md "roms\Sports\Boxing"
md "roms\Sports\Bull Fighting"
md "roms\Sports\Cards"
md "roms\Sports\Darts"
md "roms\Sports\Dodgeball"
md "roms\Sports\Fishing"
md "roms\Sports\Football"
md "roms\Sports\Golf"
md "roms\Sports\Handball"
md "roms\Sports\Hang Gliding"
md "roms\Sports\Hockey"
md "roms\Sports\Horse Racing"
md "roms\Sports\Horseshoes"
md "roms\Sports\Misc"
md "roms\Sports\Multiplay"
md "roms\Sports\Ping Pong"
md "roms\Sports\Pool"
md "roms\Sports\Rugby Football"
md "roms\Sports\Shuffleboard"
md "roms\Sports\Skateboarding"
md "roms\Sports\Skiing"
md "roms\Sports\SkyDiving"
md "roms\Sports\Soccer"
md "roms\Sports\Sumo"
md "roms\Sports\Swimming"
md "roms\Sports\Tennis"
md "roms\Sports\Track and Field"
md "roms\Sports\Volleyball"
md "roms\Sports\Wrestling"
